
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Harvard University', 1, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Stanford University', 2, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California-Berkeley', 4, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Cambridge', 5, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Massachusetts Institute of Technology (MIT)', 5, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, Berkeley', 5, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Princeton University', 6, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('California Institute of Technology', 6, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Columbia University', 8, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Chicago', 9, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Oxford', 10, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Yale University', 11, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, Los Angeles', 12, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Cornell University', 13, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Pennsylvania', 15, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, San Diego', 15, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Washington', 16, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, San Francisco', 18, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Johns Hopkins University', 18, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Swiss Federal Institute of Technology Zurich', 19, 'Switzerland', 'CH');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The Johns Hopkins University', 19, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Tokyo', 20, 'Japan', 'JP');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University College London', 21, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Michigan - Ann Arbor', 22, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Michigan-Ann Arbor', 23, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Imperial College London', 24, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Illinois at Urbana-Champaign', 25, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Northwestern University', 25, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Toronto', 26, 'Canada', 'CA');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Kyoto University', 26, 'Japan', 'JP');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('New York University', 27, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The Imperial College of Science, Technology and Medicine', 27, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Wisconsin - Madison', 28, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of British Columbia', 31, 'Canada', 'CA');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Washington University in St. Louis', 31, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Duke University', 32, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Colorado at Boulder', 32, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Rockefeller University', 33, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Minnesota, Twin Cities', 33, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Sorbonne University', 36, 'France', 'FR');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Melbourne', 38, 'Australia', 'AU');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Maryland, College Park', 38, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of North Carolina at Chapel Hill', 39, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Pierre and Marie  Curie University - Paris 6', 40, 'France', 'FR');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Utrecht University', 40, 'Netherlands', 'NL');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Vanderbilt University', 41, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Paris-Sud (Paris 11)', 41, 'France', 'FR');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Pierre and Marie Curie University - Paris 6', 42, 'France', 'FR');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Copenhagen', 43, 'Denmark', 'DK');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Texas Southwestern Medical Center at Dallas', 43, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Texas at Austin', 44, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Karolinska Institute', 44, 'Sweden', 'SE');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, Santa Barbara', 45, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of California, Irvine', 46, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Edinburgh', 47, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Heidelberg University', 47, 'Germany', 'DE');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Technical University Munich', 48, 'Germany', 'DE');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('The University of Manchester', 48, 'United Kingdom', 'GB');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('Pennsylvania State University - University Park', 49, 'United States', 'US');
INSERT INTO `Universite` (`universite`, `rang`, `pays`, `iso`) VALUES ('University of Southern California', 50, 'United States', 'US');
